### PR TITLE
Finishing sarex.md

### PR DESCRIPTION
**Pull request by migue802**

### CODE REVIEW

**Comment by omsenjalia** [comment]
Oke

**Comment by migue802** [comment]
@omxpro done :D

**Comment by omsenjalia** [comment]
Ok

**Comment by omsenjalia** [comment]
Ty for the pr

**Comment by omsenjalia** [comment]
There is now new things to work on...

**Comment by omsenjalia** [comment]
I've made placeholder's which I'll add to summary.md later as I have to go for a walk rn

**Comment by migue802** [comment]
nice

**Pull request merged**
