### PR TITLE
Capitalation on words and fixing Server Guides intro

### PR DESCRIPTION
**Pull request by migue802**
(sorry for making too much PR lol)

### CODE REVIEW

**Comment by migue802** [comment]
Alr nvm i just saw that you renamed ServerGuides to Server to rolling back changes and just fix the grammar errors

**Comment by omsenjalia** [comment]
Lemme see

**Comment by omsenjalia** [comment]
@migue802 I don't it needs any updates as I have renamed it to Server for a reason

**Comment by migue802** [comment]
@omxpro I've edited it in the second push

**Comment by omsenjalia** [comment]
> @omxpro I've edited it in the second push

Lemme see

**Comment by omsenjalia** [comment]
@migue802 push latest changes plz

**Comment by migue802** [comment]
I didn't? Let me see...

**Comment by migue802** [comment]
@omxpro https://github.com/DBH-Docs/Documentation/pull/2/commits/3044b8b5b7b81aad9034f703514abdf974d21ef6

**Comment by omsenjalia** [comment]
You didn't add rdb

**Comment by migue802** [comment]
oh sorry i see you fixed it

**Comment by omsenjalia** [comment]
Fixed what?

**Comment by migue802** [comment]
nvm i think it fixed by itself lol

**Comment by migue802** [comment]
image

**Comment by omsenjalia** [comment]
> nvm i think it fixed by itself lol

Okay then. Closing

**Comment by omsenjalia** [comment]
> image

Ooh that

**Comment by omsenjalia** [comment]
Merged

**Comment by omsenjalia** [comment]
Ty for the pr

**Comment by migue802** [comment]
Np! I'm also make nodejs docs for server creation

**Pull request merged**
