### PR TITLE
[DON'T MERGE YET, DBH DBs BROKEN] Gitea doc

### PR DESCRIPTION
**Pull request by migue802**
idk why but database creation are broken so i can't make a gitea server correctly to make the docs

### CODE REVIEW

**Comment by omsenjalia** [comment]
> idk why but database creation are broken so i can't make a gitea server correctly to make the docs

I'll add it whenever free

**Comment by omsenjalia** [comment]
Add means make a server

**Comment by migue802** [comment]
but that's the problem... i can't create the gitea server because MySQL server is broken and for configuration is vital

**Comment by omsenjalia** [comment]
@migue802 can you pull latest changes

**Comment by migue802** [comment]
image
Uhh... can you? lmfao

**Comment by omsenjalia** [comment]
> image Uhh... can you? lmfao

You just need to pull latest changes

**Comment by migue802** [comment]
but it says that the're are too complex... i'ma try in vs code let me a min

**Comment by migue802** [comment]
alr fixed it

**Comment by omsenjalia** [comment]
Noice

**Comment by omsenjalia** [comment]
I'll be adding some changes soon

**Comment by migue802** [comment]
> Noice


yes very lmao because it's the first time that I make a manual merge

**Comment by migue802** [comment]
> I'll be adding some changes soon

alright

**Comment by omsenjalia** [comment]
Pushed new changes

**Comment by migue802** [comment]
alr it seems that it haves no conflicts

**Comment by omsenjalia** [comment]
Btw what's the progress

**Comment by migue802** [comment]
> Btw what's the progress

waiting until MySql server is up again... let me see if it's up now

**Comment by migue802** [comment]
nope, db still down

**Pull request closed without merging**
