### PR TITLE
Adding node.js server guide + images + credits

### PR DESCRIPTION
**Pull request by migue802**

### CODE REVIEW

**Comment by dominnya** [comment]
Looks pog

**Comment by omsenjalia** [comment]
Ok

**Comment by migue802** [comment]
Thanks :D

**Comment by migue802** [comment]
@Domin-MND @omxpro Is everything ok? I added Node.js into summary too

**Comment by omsenjalia** [comment]
@Domin-MND should I make @migue802 a contributer?

**Comment by migue802** [comment]
OwO

**Pull request merged**
